name: 'json_dynamic_widget'
description: 'A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.'
repository: 'https://github.com/peiffer-innovations/json_dynamic_widget/tree/main/json_dynamic_widget'
version: '7.0.0+2'

environment:
  sdk: '>=3.0.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'

dependencies:
  child_builder: '^2.0.1'
  collection: '^1.17.1'
  dynamic_widget_annotation: '^1.1.0'
  execution_timer: '^1.0.3+4'
  flutter:
    sdk: 'flutter'
  form_validation:
  interpolation:
  json_class:
  json_conditional:
  json_schema:
  json_theme:
  # needed to resolve a bug with build_runner and logging@1.2.0
  logging: '>=1.0.0 <1.2.0'
  meta: '^1.9.1'
  template_expressions:
  uuid:
  yaml_writer:
  yaon:

dev_dependencies:
  build_runner: '^2.3.3'
  flutter_lints: '^2.0.3'
  flutter_test:
    sdk: 'flutter'
  json_dynamic_widget_codegen: '^1.0.0'

# dependency_overrides:
#   dynamic_widget_annotation:
#     path: ../annotation
#   json_dynamic_widget_codegen:
#     path: ../codegen
#   json_theme:
#     path: ../../json_theme/json_theme

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
